# Generated by Django 5.0.1 on 2024-01-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thought', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_reply',
            name='text',
            field=models.CharField(default='comment reply', max_length=264),
        ),
        migrations.AlterField(
            model_name='comment',
            name='thought',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='thought.thought'),
        ),
    ]
