# Generated by Django 4.2.1 on 2024-01-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thought', '0003_alter_comment_reply_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='text',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
