# Generated by Django 5.0.1 on 2024-01-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('city', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
